language: python
python:
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- 3.7-dev
- nightly
install: true
script:
- python setup.py install
deploy:
  provider: pypi
  user: Chadsr
  password:
    secure: na3J3tqpasJ9D3CYh6nGTdflApmkNsTZwTNVvjcfZLaVdInJaDyTwYgai5bQK8Q+XM19mldvKjb2e5tx70xPzvJqv33MTSaLEwfa7O6JeROx57vGs/3vtpeaOIRF2Eh1jRrysOt43kjSE4DIJP58uYvWKWUkNhqdPFd7PcXtbVLyUj5dZ8rNDWAvEXMaPgm1X16O0fi5V5vY60okuFcGuxX4thVLna+II7QhXbcQMX7SeQtnUIl8chgfJwu8EGIgGilHdFsyKCH8Zsrlq5h/NzVBu0nCrEVU31Tz7Pyzc1Cm5BVkuySZjE4mDx4olazbNRxidsZeaiGYI84XqhD1ppxC/j70+G28w2RaAkQiL/VGKUGOfImtOGt7CbdkicxDRma/xEBTWNiRPGd0ITs4GUAfrXguRJV2UhDhqS7NzZyJ4GMBWImJ1yIa4ftOcRxH8gScTqWTY5TenpcVxmTYQhU8DpaEhN5FpVHhoq9CbZemzgIzJ1n7ivoelXcFnifJfj2NWYlnSlduDwjtZ7zT9okdfkskDDf+Hcw3ajRMaeoXpZeRv2ejGTHIHVkHaj8OwHpqt5uu3MuYI+2euWjkeTQ2YaS2W/0fdXkiHqZeUA38RI6SUxIpH/fpXaKyxXavKc781Vs2hvk8JFe4htXguDdg3uSTlQxdmh7tKuttfuM=
  on:
    branch: master
    tags: true
