language: python
python:
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- 3.7-dev
- nightly
install: true
script:
- python setup.py install
deploy:
  provider: pypi
  user: Chadsr
  password:
    secure: dSfgQQ9wsJ1VYsWXf/nG/7nNLwlO0fkKxPNElUN+od0wf6AQiLbmO2QjO28o76K/SEXh+iqSE/dRzOKsGTpYSOEWlntxhb4IOC6dFzU1Cfw1RBDLRHwEUsAuh7W0REoVTL7WHot+XEwvzsIxoR3zRAx8+UmcOXX/e8NaxdV7CRmY8bUqv1bDpcvhXRLwcPd72CpQoP4/GAmKiTzLHXGbWBBua+X8sMe5M8QNVLL7qAMXCUtjoXbYBov2TJlL3/8JrFclIs+xySVmyhldhNWsESiFitwA7D8OpdCyvFOS6e92fAfvcLsWvxc7/MWVWOdPATMuL2y4AW2ISb0c8MicDxDi9JyOT7Aq/GOS8NbMQw0hOlBRPASzbU4uKZX5Tp7C0BKHUsgXkK5qrrKLSxgCXJsFoXOsAgKSdBHWicCXpZCq2KYnlG6SywjfvEWwtvgieM2Hi2EgMeGQKEYDyU1jbS6jAguzU5vkxvslEciK5iM64uTeEdEK43becxhbW4ieLJ63mdzaIoJeWo0K1lOck+260eUdKJ9O//RZOoYEYjDD43d42QRlbEXO7lXjFIIc5YQhGWBAQRwnlcXSJyOV7L52f8pxjKOltC1Vh5i+DHqHwshdY2NO1ZyNVyT57FQImQyZf4uhN2jdpUsytdeOuE66lls2tKy64P0GBmEHynI=
  provider: launchpad
  slug: "~chadsr/nordnm/+git/main"
  oauth_token:
    secure: BvmQXAmpqG2/Th5Cv5stdrBU2TiT9+wgEOryeW5KRkjajU/DaS2jkmHEs1bfgGdL3L5LJmlM+/N5+KvGDChFus/NL5ott9gzi60y7BNpBb50g5EQo8vMADbKEZ4vYxrFD/lecY+KNkjmfgWgvZghUZPkC8L55CHAqS0mOjYWukEdxZoUe8M+Sys2oiqjx2C1TL5Gqu6Lh2AnEZBzfLxypJfTCuqcRIc23QmbcBlqISwbJ5VXdtwLtJU8yQ4yp3vo5Mlw5583wUT2wMOiwzTCi6ft1WXOFfPQ4KMS+SdTPhHzNpgdT6eQZJTahcjpvfGPGdBxWE709DE0nMzO7vBYq5Ae9BYGpGVMZSsvld/fLOeNZlKrO1/ha2IgPk5QjEqDfT+Pbn7VXUjKPtUd3o8U6/Uwg/wyHxhOvq4CJtWkMPKUnKntgu34RCCKtalL4BuVvnB1oaWzpltE0Q96VySLn7lvG3KnF/2LgNylnL3O29bVawR3Qmpz8EhZL2Uf0HZSr0r1uJGyOuoQvyTIkLdnWro18unRqOuV2yNL+eQcQJv5Ztd9oYaXOhITGd7OQ6CUcK/Q3lxFnOqx4a2wZ+H9Tvw8P510vlAYrz7yM356SyYGyPVLLZVJMQ5/LGRHAeobRstf8ZF/4mukalygVg13/pmtwLlnwg27a6XGIoEQXDg=
  oauth_token_secret:
    secure: U+TOShtr5shj/FjGSXBZd6wSHfF861QQcqibBP6QFZZR4LUkvcni4jTzf2ltBshACv9Yi3dVOeluue94lDQQ8GKa/AQEt+NKI4Ra/Fe4KJ9/HwWIlOY12BRsu4Ff5LVrAloEfbPEOcrQDgwb3wWjp9G1Z/X5bRoXQcSiCcHwHwPNEpo4onGEB+lD8gET+ISjOcRIPG/AWCTu41eZ5KU4+kgMsNN3OumasV8GLHTtovwqE3AFDPnf/oatxxqAiiHvuw2X04f0K70OBsuhI1RMcIkOPLwBx4gXNP/4sR8q1+Yp+wj0fKyUNArMv/b2xGJEeKwbQYJNpClLj6t2Pr/gEmBIHt5kXMK6JAaZ8ppxuCOat4HiqRp3o6RGDpvmjJgaZU6XeKYmLdoKmzRHzN3cFx2UPf5wHw+BkK0J2ebNuvjYS2cwBk8vgSmLxysLZm5fbTZOSdPqvb7PJVgyrYpiL+yJSieQ7cT4rH7FsVbcVPgDdBle50oRyhXkR/SapI1wQnXWwZz9EFjRS40l6nXJJdLxTX9/kq5Nr3X55OXhTm3F9OzKHAn1wcFSqksEWLovu7hKGCJ4n/gQOLvvyvRMIB+pbMT3i7CZirtK0JNFhd5w/i0WY/7CORPUQXttRKF6MWb9oIkKZbKeAcXGeJrbw0D0QatH9a5iOVyIxu2/rj8=
  on:
    branch: master
    tags: true
