language: python
python:
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- 3.7-dev
- nightly
install: true
script:
- python setup.py install
deploy:
- provider: pypi
  user: Chadsr
  password:
    secure: dSfgQQ9wsJ1VYsWXf/nG/7nNLwlO0fkKxPNElUN+od0wf6AQiLbmO2QjO28o76K/SEXh+iqSE/dRzOKsGTpYSOEWlntxhb4IOC6dFzU1Cfw1RBDLRHwEUsAuh7W0REoVTL7WHot+XEwvzsIxoR3zRAx8+UmcOXX/e8NaxdV7CRmY8bUqv1bDpcvhXRLwcPd72CpQoP4/GAmKiTzLHXGbWBBua+X8sMe5M8QNVLL7qAMXCUtjoXbYBov2TJlL3/8JrFclIs+xySVmyhldhNWsESiFitwA7D8OpdCyvFOS6e92fAfvcLsWvxc7/MWVWOdPATMuL2y4AW2ISb0c8MicDxDi9JyOT7Aq/GOS8NbMQw0hOlBRPASzbU4uKZX5Tp7C0BKHUsgXkK5qrrKLSxgCXJsFoXOsAgKSdBHWicCXpZCq2KYnlG6SywjfvEWwtvgieM2Hi2EgMeGQKEYDyU1jbS6jAguzU5vkxvslEciK5iM64uTeEdEK43becxhbW4ieLJ63mdzaIoJeWo0K1lOck+260eUdKJ9O//RZOoYEYjDD43d42QRlbEXO7lXjFIIc5YQhGWBAQRwnlcXSJyOV7L52f8pxjKOltC1Vh5i+DHqHwshdY2NO1ZyNVyT57FQImQyZf4uhN2jdpUsytdeOuE66lls2tKy64P0GBmEHynI=
- provider: launchpad
  slug: "~chadsr/nordnm/+git/main"
  oauth_token:
    secure: YUe8gVOCMA/xCz+gF2sNAymsPwFJjyEQ6PaWEqLaDIotBUZtrnWDGkXv/E9UQWntm6Xc9mKs0fdq8AGNwdHUF38ie6jAnBe5XPldZrmYu1yxhr4lmR0E+49JkczwIaqQ3K+YgOif2CqGQzPu5kzNX0VEOqt96EkZ5W7tdqqqoiQwg6DkMOMoLERuFtcyP6sjcjOfeMFfU+yTza4DhtIvzRD9ZDXz/NNRcOVJQPEzoY7x+XgYorO51g/ji77KzRY48CRGjG1N+qGkEvdT721+ZkfEVuifcQzvE52zu+AiooZeOfZUxnDHGUhQVBTyrHZWBSKgMeCOCZyIdB+Uf3/p1sURJcX4NEjcVbnmAmuh5gPzqxqQeNvrCoh8tBiyXiLYmTUPL/G2dSyUsjmhgO75drbn5aLEHXstyiLO3ameY7iogpwpXAwNh+fTnNGFvvdQ8NpoNrhk0ciTEDtoWSEECndgZmlYefv+9YEKZ93MW2kej++TqgFlqS2L9UL5xHsa7exphf/ZZaoYCBqvbANJ6JsZ4j0nK9YimB7p0GULvBrAJ5vAdw5mb+9wKpDEzvOhHR0WzJc22odFpj3M35R4JdKAilMNXyVPcfL8/KmLIXp2T0LGU1RS9q8XaJce3Sa8nPWW7nPJOMSn18rp4mLc0XwxTxdjd3VzvIvNOxum5ic=
  oauth_token_secret:
    secure: A9zNq/XOR3XLnLsfOvxiat6SRTbKMeUl0xTTagJWX/nLmjB873Lg7OzjbwFAAE+37jmm0+Gv60+57r+q8RocIHjMaSQBDwooqS9bHPd0NoFyPihM4Rt7BZGYXWTk8d7zKJAaK8rIXpRhAap/tKkYf0a25vxnt9PeCgjxC6SEunI0k7r0LCXSWt464lL9yldwOpFLJwaQ7guRJIoPRWKBa2K+3FRNTwWeP1UWPXS+viMZQiA7tRK8hjAu2/KVAVbaUc9X3nMfevi/zhABXPrGwdEl5Fx/dKAfrd9hLsfwIZ5AHJF7BeCkBzLP87iw/S+AXFRrPAFy41aUt4QmReG8CCp3pQgmtIqn0VQzrvGxNTDQH/NTk1uCdDagPiuYiPisQnytnvEGwM4A93jEqBQ/tXAiGAOVLXh/QfzUoCB+4FMC+QZnbUtyrwRkGnbyDnwRMYdWlimLYiYFyV44lx7rBGfGa5lVuw4V7jTynWpfGuOAVGWRBS6Df6FhnJ2lHhtF5whEaD4mtmmJYz1vFQUMq/WgL35qFduJ4ihRzlg1bso1nNSgM6Ns09bgVwQ2WII3DckbkENSKSvMi5YbRmOLOBhkhh63UwOtqQKGNrhKwlX5BY/Z/hH6UkOxv0b2M/b5KG4C8oIcdBkquSoOKFE2Q6ctsiznz5bI8icyoQ5E6vQ=
  on:
    branch: master
    tags: true
